[package]
name = "dropout-pairwise"
version = "0.1.0"
authors = ["khun <bahkhun@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lt-fm-index = "0.3.1"
bio = "0.37.0"
fm-index = "0.1.2"
serde = "1.0.127"
bincode = "1.3.3"

[dev-dependencies]