[workspace]
members = [
    "sigalign",
    "sigalign-py",
    "examples/sigalign-demo-aligner",
    "examples/sigalign-demo-wasm",
]
exclude = [
    "examples/sigalign-demo-web",
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3