[workspace]
members = [
    "sigalign",
    "sigalign-py",
    "sigalign-demo-bin/sigalign-demo-aligner",
]
exclude = [
    "sigalign-demo-web"
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3