[package]
name = "dropout-pairwise"
version = "0.1.0"
authors = ["khun <bahkhun@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
num = "0.4.0"
lt-fm-index = "0.4.0"
bio = "0.37.0"
fm-index = "0.1.2"
serde = "1.0.127"
serde_json = "1.0.68"
bincode = "1.3.3"
float-cmp = "0.9.0"
rusqlite = "0.26.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false