name: build_and_test

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  TEST_ENVIRONMENT: ci

jobs:
  build-on-majors:
    name: "Build on major platforms"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust toolchain
      run: rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  wasm-build:
    name: "Build as WASM"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update
    - name: Add build target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --verbose
